"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[ó°€µ](bold green)'
error_symbol = '[ó°€µ](bold red)'
vimcmd_symbol = '[ó°€µ](bold purple)'

[package]
format = '[\[$symbol$version\]]($style) '
symbol = 'ó°– '

[golang]
format = '[\[$symbol$version($mod_version)\]](bold cyan) '
symbol = 'î˜§ '

[java]
format = '[\[${symbol}(${version})\]]($style)'
symbol = 'ó°¬· '

[nodejs]
format = '[\[$symbol$version\]]($style) '

[git_branch]
format = '[\[$symbol$branch(:$remote_branch)\]]($style) '
symbol = 'ï‡’ '

# [git_status]
# conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
# up_to_date = 'âœ“'
# untracked = 'ğŸ¤·'
# stashed = 'ğŸ“¦'
# modified = 'ğŸ“'
# staged = '[++\($count\)](green)'
# renamed = 'ğŸ‘…'
# deleted = 'ğŸ—‘'

[docker_context]
format = '[\[$symbol$context\]]($style) '
symbol = 'ó°¡¨ '

[kubernetes]
format = '[\[$symbol($user on )($cluster in )$context\($namespace\)\]]($style) '
disabled = true 

